name: jupyterlab-deck-test

channels:
  - conda-forge
  - nodefaults
  - conda-forge/label/jupyterlab_fonts_alpha
  - conda-forge/label/jupyterlite_core_beta
  - conda-forge/label/jupyterlite_pyodide_kernel_alpha

dependencies:
  - python >=3.10,<3.13
  ### environment-base.yml ###
  - doit-with-toml
  - ipywidgets >=7
  - jupyterlab >=4.0.7,<5
  - jupyterlab-fonts >=3.0.0a2
  - notebook >=7.0.5,<8
  - pip
  - python >=3.8,<3.13
  - python-dotenv
  ### environment-base.yml ###
  ### environment-build.yml ###
  # runtimes
  - nodejs >=20,<21
  # host app
  - ipywidgets >=7
  # build
  - flit >=3.9.0,<4.0.0
  - twine
  ### environment-build.yml ###
