name: jupyterlab-deck-lint

channels:
  - conda-forge
  - nodefaults
  - conda-forge/label/jupyterlab_fonts_alpha

dependencies:
  - python >=3.10,<3.12
  ### environment-base.yml ###
  - doit-with-toml
  - ipywidgets >=7
  - jupyterlab >=4,<5
  - jupyterlab-fonts >=3.0.0a1
  - pip
  - python >=3.7,<3.12
  ### environment-base.yml ###
  ### environment-build.yml ###
  # runtimes
  - nodejs >=16,<17
  # host app
  - ipywidgets >=7
  # build
  - flit >=3.7.1
  - twine
  ### environment-build.yml ###
  ### environment-lint.yml ###
  # formatters
  - black
  - isort
  - ssort
  - docformatter
  - robotframework-tidy >=3.3
  # linters
  - robotframework-robocop >=2.6
  - pyflakes
  ### environment-lint.yml ###
  ### environment-robot.yml ###
  - robotframework >=6
  - robotframework-pabot
  # browser
  - firefox
  - geckodriver
  - robotframework-jupyterlibrary >=0.4.1
  - lxml
  ### environment-robot.yml ###
