name: jupyterlab-deck-test

channels:
  - conda-forge
  - nodefaults

dependencies:
  # a more precise python pin is added in CI
  ### environment-base.yml ###
  - doit-with-toml
  - ipywidgets >=7
  - jupyterlab >=4,<5
  - jupyterlab-fonts >=3.0.0a1
  - pip
  - python >=3.7,<3.12
  ### environment-base.yml ###
  ### environment-build.yml ###
  # runtimes
  - nodejs >=16,<17
  # host app
  - ipywidgets >=7
  # build
  - flit >=3.7.1
  - twine
  ### environment-build.yml ###
  ### environment-test.yml ###
  # test
  - pytest-cov
  - pytest-html
  ### environment-test.yml ###
  ### environment-robot.yml ###
  - robotframework >=6
  - robotframework-pabot
  # browser
  - firefox
  - geckodriver
  - robotframework-jupyterlibrary >=0.4.1
  - lxml
  ### environment-robot.yml ###
