dependencies:
  ### environment-base.yml ###
  - doit-with-toml
  - ipywidgets >=7
  - jupyterlab >=4.0.7,<5
  - jupyterlab-fonts >=3.0.0a2
  - notebook >=7.0.5,<8
  - pip
  - python >=3.8,<3.13
  - python-dotenv
  ### environment-base.yml ###
