name: jupyterlab-deck-test

channels:
  - conda-forge
  - nodefaults
  - conda-forge/label/jupyterlab_fonts_alpha

dependencies:
  - python >=3.10,<3.12
  ### environment-base.yml ###
  - doit-with-toml
  - ipywidgets >=7
  - jupyterlab >=4,<5
  - jupyterlab-fonts >=3.0.0a1
  - pip
  - python >=3.7,<3.12
  ### environment-base.yml ###
  ### environment-build.yml ###
  # runtimes
  - nodejs >=16,<17
  # host app
  - ipywidgets >=7
  # build
  - flit >=3.7.1
  - twine
  ### environment-build.yml ###
