name: jupyterlab-deck-test

channels:
  - conda-forge
  - nodefaults
  - conda-forge/label/jupyterlab_fonts_alpha
  - conda-forge/label/jupyterlite_core_beta
  - conda-forge/label/jupyterlite_pyodide_kernel_alpha

dependencies:
  # a more precise python pin is added in CI
  ### environment-base.yml ###
  - doit-with-toml
  - ipywidgets >=7
  - jupyterlab >=4.0.6,<5
  - jupyterlab-fonts >=3.0.0a1
  - notebook >=7.0.4,<8
  - pip
  - python >=3.8,<3.13
  - python-dotenv
  ### environment-base.yml ###
  ### environment-build.yml ###
  # runtimes
  - nodejs >=20,<21
  # host app
  - ipywidgets >=7
  # build
  - flit >=3.9.0,<4.0.0
  - twine
  ### environment-build.yml ###
  ### environment-test.yml ###
  # test
  - pytest-cov
  - pytest-html
  ### environment-test.yml ###
  ### environment-robot.yml ###
  - robotframework >=6.1
  - robotframework-pabot
  # browser
  - firefox 115.*
  - geckodriver
  - robotframework-jupyterlibrary >=0.5.0
  - lxml
  ### environment-robot.yml ###
