name: jupyterlab-deck-demo

channels:
  - conda-forge
  - nodefaults
  - conda-forge/label/jupyterlab_fonts_alpha
  - conda-forge/label/jupyterlite_core_beta
  - conda-forge/label/jupyterlite_pyodide_kernel_alpha

dependencies:
  - python >=3.11,<3.12
  ### environment-base.yml ###
  - doit-with-toml
  - ipywidgets >=7
  - jupyterlab >=4.0.7,<5
  - jupyterlab-fonts >=3.0.0a2
  - notebook >=7.0.5,<8
  - pip
  - python >=3.8,<3.13
  - python-dotenv
  ### environment-base.yml ###
  ### environment-build.yml ###
  # runtimes
  - nodejs >=20,<21
  # host app
  - ipywidgets >=7
  # build
  - flit >=3.9.0,<4.0.0
  - twine
  ### environment-build.yml ###
  ### environment-lint.yml ###
  # formatters
  - black
  - ssort
  - ruff
  - robotframework-tidy >=3.3
  # linters
  - robotframework-robocop >=2.6
  ### environment-lint.yml ###
  ### environment-docs.yml ###
  # docs
  - docutils >=0.18
  - mdit-py-plugins <0.4.0
  - myst-nb
  - pydata-sphinx-theme
  - sphinx >=5.1,<6
  - sphinx-autobuild
  - sphinx-copybutton
  # check
  - hunspell
  - hunspell-en
  - pytest-check-links
  # lite
  - python-libarchive-c
  - jupyterlite-core ==0.2.0b1
  - jupyterlite-pyodide-kernel ==0.2.0a2
  ### environment-docs.yml ###
  ### environment-test.yml ###
  # test
  - pytest-cov
  - pytest-html
  ### environment-test.yml ###
  ### environment-robot.yml ###
  - robotframework >=6.1
  - robotframework-pabot
  # browser
  - firefox 115.*
  - geckodriver
  - robotframework-jupyterlibrary >=0.5.0
  - lxml
  ### environment-robot.yml ###
