name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  CACHE_EPOCH: 3

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILDING_IN_CI: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

    - name: install (conda)
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: .binder/environment.yml
        miniforge-variant: Mambaforge
        use-mamba: true

      - name: Build dist
        shell: bash -l {0}
        run: doit dist

      - name: Upload (dist)
        uses: actions/upload-artifact@v3
        with:
          name: jupyterlab-deck dist ${{ github.run_number }}
          path: ./dist
